---

##
web_ui_hostname: "irma.local"

nginx_configs:
  gzip:
    - gzip on
    - gzip_disable "msie6"
    - gzip_comp_level 6
    - gzip_buffers 16 8k
    - gzip_http_version 1.1
    - gzip_types text/plain text/css application/json application/x-javascript text/javascript application/javascript
  http:
    - server_names_hash_bucket_size 64

nginx_sites:
  irma-web-ui:
    - listen 80
    - listen [::]:80 ipv6only=on
    - server_name {{hostname}} www.{{hostname}}
    - client_max_body_size 100m
    - location ~ /\.ht {
        deny all;
      }
    - location / {
        expires -1;
        add_header Pragma "no-cache";
        add_header Cache-Control "no-store, no-cache, must-revalidate, post-check=0, pre-check=0";
        root {{web_ui_install_dir}}/dist;
        try_files $uri $uri/ /index.html =404;
      }
    - error_log {{nginx_log_dir}}/{{hostname}}.error.log
    - access_log {{nginx_log_dir}}/{{hostname}}.access.log
